// Mocks generated by Mockito 5.4.4 from annotations
// in pomodoro_app/test/providers/pomodoro_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pomodoro_app/domain/entities/session_history.dart' as _i11;
import 'package:pomodoro_app/domain/entities/timer_config.dart' as _i5;
import 'package:pomodoro_app/domain/repositories/pomodoro_repository.dart'
    as _i2;
import 'package:pomodoro_app/domain/usecases/pomodoro_usecases.dart' as _i3;
import 'package:pomodoro_app/domain/usecases/statistics_usecases.dart' as _i10;
import 'package:pomodoro_app/presentation/providers/music_service.dart' as _i9;
import 'package:pomodoro_app/presentation/providers/settings_service.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePomodoroRepository_0 extends _i1.SmartFake
    implements _i2.PomodoroRepository {
  _FakePomodoroRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCustomTimerConfigs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCustomTimerConfigs extends _i1.Mock
    implements _i3.GetCustomTimerConfigs {
  MockGetCustomTimerConfigs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PomodoroRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePomodoroRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PomodoroRepository);

  @override
  _i4.Future<List<_i5.TimerConfig>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.TimerConfig>>.value(<_i5.TimerConfig>[]),
      ) as _i4.Future<List<_i5.TimerConfig>>);
}

/// A class which mocks [SaveTimerConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTimerConfig extends _i1.Mock implements _i3.SaveTimerConfig {
  MockSaveTimerConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PomodoroRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePomodoroRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PomodoroRepository);

  @override
  _i4.Future<void> call(_i5.TimerConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DeleteTimerConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTimerConfig extends _i1.Mock implements _i3.DeleteTimerConfig {
  MockDeleteTimerConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PomodoroRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePomodoroRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PomodoroRepository);

  @override
  _i4.Future<void> call(_i5.TimerConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i6.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get soundEnabled => (super.noSuchMethod(
        Invocation.getter(#soundEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i7.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i7.ThemeMode.system,
      ) as _i7.ThemeMode);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setNotificationsEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSoundEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setSoundEnabled,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleTheme() => (super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setDarkMode(bool? isDark) => (super.noSuchMethod(
        Invocation.method(
          #setDarkMode,
          [isDark],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setThemeMode(_i7.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLocale(_i8.Locale? locale) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [locale],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MusicService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicService extends _i1.Mock implements _i9.MusicService {
  MockMusicService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.MusicTrack> get tracks => (super.noSuchMethod(
        Invocation.getter(#tracks),
        returnValue: <_i9.MusicTrack>[],
      ) as List<_i9.MusicTrack>);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void selectTrack(_i9.MusicTrack? track) => super.noSuchMethod(
        Invocation.method(
          #selectTrack,
          [track],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i9.MusicTrack> getTracksByCategory(_i9.MusicCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTracksByCategory,
          [category],
        ),
        returnValue: <_i9.MusicTrack>[],
      ) as List<_i9.MusicTrack>);

  @override
  _i4.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SaveSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveSession extends _i1.Mock implements _i10.SaveSession {
  MockSaveSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(_i11.SessionHistory? session) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [session],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
